// Mock book database with comprehensive data
const bookDatabase: Book[] = [
    // Science Fiction
    {
      id: '1',
      title: 'Dune',
      author: 'Frank Herbert',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Science Fiction',
      year: '1965',
      rating: 4.7,
      totalPages: 412,
    },
    {
      id: '2',
      title: 'Project Hail Mary',
      author: 'Andy Weir',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Science Fiction',
      year: '2021',
      rating: 4.9,
      totalPages: 496,
    },
    {
      id: '3',
      title: 'The Three-Body Problem',
      author: 'Liu Cixin',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Science Fiction',
      year: '2008',
      rating: 4.3,
      totalPages: 416,
    },
    {
      id: '4',
      title: 'Neuromancer',
      author: 'William Gibson',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Science Fiction',
      year: '1984',
      rating: 4.0,
      totalPages: 271,
    },
    
    // Self-Help
    {
      id: '5',
      title: 'Atomic Habits',
      author: 'James Clear',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Self-Help',
      year: '2018',
      rating: 4.8,
      totalPages: 320,
    },
    {
      id: '6',
      title: 'The 7 Habits of Highly Effective People',
      author: 'Stephen R. Covey',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Self-Help',
      year: '1989',
      rating: 4.6,
      totalPages: 381,
    },
    {
      id: '7',
      title: 'Think and Grow Rich',
      author: 'Napoleon Hill',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Self-Help',
      year: '1937',
      rating: 4.5,
      totalPages: 233,
    },
    {
      id: '8',
      title: 'Deep Work',
      author: 'Cal Newport',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Self-Help',
      year: '2016',
      rating: 4.6,
      totalPages: 296,
    },
    
    // Fantasy
    {
      id: '9',
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Fantasy',
      year: '1937',
      rating: 4.6,
      totalPages: 366,
    },
    {
      id: '10',
      title: 'Harry Potter and the Philosopher\'s Stone',
      author: 'J.K. Rowling',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Fantasy',
      year: '1997',
      rating: 4.8,
      totalPages: 223,
    },
    {
      id: '11',
      title: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Fantasy',
      year: '2007',
      rating: 4.7,
      totalPages: 662,
    },
    {
      id: '12',
      title: 'A Game of Thrones',
      author: 'George R.R. Martin',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Fantasy',
      year: '1996',
      rating: 4.6,
      totalPages: 835,
    },
    
    // Classic
    {
      id: '13',
      title: 'To Kill a Mockingbird',
      author: 'Harper Lee',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Classic',
      year: '1960',
      rating: 4.3,
      totalPages: 281,
    },
    {
      id: '14',
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Classic',
      year: '1925',
      rating: 4.2,
      totalPages: 180,
    },
    {
      id: '15',
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Classic',
      year: '1813',
      rating: 4.5,
      totalPages: 432,
    },
    {
      id: '16',
      title: '1984',
      author: 'George Orwell',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'Classic',
      year: '1949',
      rating: 4.6,
      totalPages: 328,
    },
    
    // History
    {
      id: '17',
      title: 'Sapiens: A Brief History of Humankind',
      author: 'Yuval Noah Harari',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'History',
      year: '2011',
      rating: 4.5,
      totalPages: 443,
    },
    {
      id: '18',
      title: 'Guns, Germs, and Steel',
      author: 'Jared Diamond',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'History',
      year: '1997',
      rating: 4.3,
      totalPages: 480,
    },
    {
      id: '19',
      title: 'The Wright Brothers',
      author: 'David McCullough',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'History',
      year: '2015',
      rating: 4.5,
      totalPages: 336,
    },
    {
      id: '20',
      title: 'A People\'s History of the United States',
      author: 'Howard Zinn',
      cover: 'https://via.placeholder.com/120x180',
      genre: 'History',
      year: '1980',
      rating: 4.1,
      totalPages: 729,
    },
  ];

  export default bookDatabase;